import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Theme, Search, Select, SelectItem, NumberInput, Button, Tag, Pagination, Modal, InlineNotification, Loading } from '@carbon/react';
import { ArrowUpRight, Search as SearchIcon, Reset, ArrowRight } from '@carbon/react/icons';
import { filterRecords, normalize } from './search.mjs';
import { inScope } from './scope.mjs';
import './style.scss';
import Outcome from './Outcome.jsx';
import Documents, { DocumentSummary } from './Documents.jsx';
import ResultsMap from './ResultsMap.jsx';

const currency = cents => cents == null ? 'No consta' : new Intl.NumberFormat('es-ES', { style:'currency', currency:'EUR', maximumFractionDigits:2 }).format(cents / 100);
const date = value => value ? new Intl.DateTimeFormat('es-ES', { dateStyle:'medium', timeZone:'Europe/Madrid' }).format(new Date(value)) : 'No consta';
const tagType = state => ({ Activa:'green', Próxima:'blue', Pasada:'gray', Cancelada:'red', Suspendida:'purple' })[state] || 'gray';
const mapEmbedUrl = row => row.mapQuery ? `https://www.google.com/maps?q=${encodeURIComponent(row.mapQuery)}&output=embed` : null;
const defaults = { query:'', state:'', year:'', municipality:'', minM2:'', maxM2:'', minAppraisal:'', maxAppraisal:'', minPriceM2:'', maxPriceM2:'', habitual:'', occupancy:'', charges:'', sort:'end' };
const factText = { habitual:{ yes:'Sí', no:'No', unknown:'No consta' }, occupancy:{ occupied:'Ocupado', empty:'Desocupado', unknown:'No consta' }, charges:{ present:'Con indicios', none:'Sin cargas expresas', unknown:'No consta' } };
const factValue = (facts, key) => factText[key]?.[facts?.[key]] || 'No consta';
function App() {
  const [catalog, setCatalog] = useState(null), [error, setError] = useState(''), [attempt, setAttempt] = useState(0);
  const [filters, setFilters] = useState(() => { const params = new URLSearchParams(location.search); return Object.fromEntries(Object.entries(defaults).map(([key,value]) => [key,params.get(key) || value])); });
  const [page, setPage] = useState(1), [pageSize, setPageSize] = useState(12), [selected, setSelected] = useState(null);
  useEffect(() => {
    const controller = new AbortController();
    setError('');
    fetch(`${import.meta.env.BASE_URL}data/catalog.json`, {signal:controller.signal}).then(response => { if (!response.ok) throw new Error('No se pudo descargar el catálogo.'); return response.json(); }).then(data => { if (!Array.isArray(data.records) || !Array.isArray(data.scans)) throw new Error('El catálogo tiene un formato inesperado.'); setCatalog(data); }).catch(err => { if (err.name !== 'AbortError') setError(err.message); });
    return () => controller.abort();
  }, [attempt]);
  useEffect(() => {
    const params = new URLSearchParams();
    Object.entries(filters).forEach(([key,value]) => { if (value && value !== defaults[key]) params.set(key,value); });
    history.replaceState(null,'', `${location.pathname}${params.size ? `?${params}` : ''}`);
  }, [filters]);
  function update(key,value) { setFilters(previous => ({...previous, [key]:value})); setPage(1); }
  const records = (catalog?.records || []).filter(inScope), results = filterRecords(records,filters);
  const years = Array.from({length:new Date().getFullYear()-2015}, (_,index) => String(2016+index)).reverse();
  const municipalities = [...new Map(records.flatMap(row => row.towns || []).filter(Boolean).map(town => [normalize(town), town])).values()].sort((a,b) => normalize(a).localeCompare(normalize(b), 'es'));
  const activeCount = records.filter(row => row.status === 'Activa').length;
  const nextCount = records.filter(row => row.status === 'Próxima').length;
  const select = (key,label,items) => <Select id={key} labelText={label} value={filters[key]} onChange={event => update(key,event.target.value)}><SelectItem value="" text="Todos"/>{items.map(item => Array.isArray(item) ? <SelectItem key={item[0]} value={item[0]} text={item[1]}/> : <SelectItem key={item} value={item} text={item}/>)}</Select>;
  const number = (key, label, step = 1) => <NumberInput id={key} label={label} min={0} step={step} value={filters[key]} onChange={(_, data) => update(key, String(data?.value ?? ''))}/>;
  return <Theme theme="g10">
    <a className="skip" href="#contenido">Saltar al contenido</a>
    <header className="site-header"><a className="brand" href={import.meta.env.BASE_URL}>Subastas <strong>BOE</strong><span className="brand-divider">/</span><span className="brand-subtitle">Explorador</span></a><a href="https://subastas.boe.es/" className="official">Portal oficial <ArrowUpRight size={16}/></a></header>
    <main id="contenido">
      <section className="hero"><div><p className="eyebrow">INMUEBLES · PROVINCIA DE VALENCIA</p><h1>Encuentra tu próxima<br/>oportunidad.</h1><p className="lead">Explora viviendas, locales, terrenos y otros inmuebles de toda la provincia de Valencia.</p></div><div className="hero-note"><span className="small-label">EL CATÁLOGO, EN CONSTRUCCIÓN</span><p>Datos reales.<br/>Cobertura transparente.</p><a href="#cobertura">Consultar cobertura <ArrowRight size={16}/></a></div></section>
      <section className="metrics" aria-label="Resumen del catálogo importado"><div><span>{catalog ? records.length : '—'}</span><p>Subastas en el catálogo</p></div><div><span>{catalog ? activeCount : '—'}</span><p>Activas al comprobarlas</p></div><div><span>{catalog ? nextCount : '—'}</span><p>Próximas al comprobarlas</p></div><div><span className="metric-date">{catalog ? date(catalog.generatedAt) : '—'}</span><p>Última exportación</p></div></section>
      <div className="workspace"><aside className="filters" aria-label="Filtros de búsqueda"><div className="filter-heading"><h2>Filtros</h2><Button kind="ghost" size="sm" hasIconOnly renderIcon={Reset} iconDescription="Restablecer filtros" onClick={() => {setFilters(defaults);setPage(1);}}/></div>{select('year','Año de inicio',years)}{select('state','Estado comprobado',['Activa','Próxima','Pasada','Suspendida','Cancelada','Sin confirmar'])}{select('municipality','Municipio',municipalities)}<div className="filter-group"><span className="filter-group-label">Superficie publicada (m²)</span>{number('minM2','Mínimo')}{number('maxM2','Máximo')}</div><div className="filter-group"><span className="filter-group-label">Precio tasado (€)</span>{number('minAppraisal','Mínimo',1000)}{number('maxAppraisal','Máximo',1000)}</div><div className="filter-group"><span className="filter-group-label">Precio tasado por m² (€)</span>{number('minPriceM2','Mínimo',50)}{number('maxPriceM2','Máximo',50)}</div>{select('habitual','Vivienda habitual',[['yes','Sí'],['no','No'],['unknown','No consta']])}{select('occupancy','Ocupación documentada',[['occupied','Ocupado'],['empty','Desocupado'],['unknown','No consta']])}{select('charges','Cargas documentales',[['present','Con indicios'],['none','Sin cargas expresas'],['unknown','No consta']])}<p className="filter-note">Ámbito fijo: inmuebles de la provincia de Valencia. Superficie, tasación y estados se extraen solo de afirmaciones explícitas en los anexos; «No consta» no equivale a ausencia.</p></aside>
      <section className="results" aria-label="Resultados de búsqueda"><Search id="query" size="lg" labelText="Buscar subastas" placeholder="Municipio, descripción o identificador…" closeButtonLabelText="Borrar búsqueda" value={filters.query} onChange={event => update('query',event.target.value)}/><div className="results-heading"><div><h2>Explorar subastas</h2><p aria-live="polite">{catalog ? `${results.length} resultados en el catálogo` : 'Cargando catálogo…'}</p></div><Select id="sort" inline labelText="Ordenar" value={filters.sort} onChange={event => update('sort',event.target.value)}><SelectItem value="end" text="Fecha de cierre"/><SelectItem value="start" text="Inicio más reciente"/><SelectItem value="value" text="Menor valor de subasta"/></Select></div>
      {error ? <div role="alert"><InlineNotification kind="error" title="No se pudo cargar el catálogo" subtitle={error} hideCloseButton/><Button kind="tertiary" onClick={() => setAttempt(attempt+1)}>Reintentar</Button></div> : !catalog ? <Loading withOverlay={false} description="Cargando datos de subastas"/> : <><div className="catalog-notice">Inmuebles de Valencia · Histórico desde 2016 incompleto. Consulta los periodos recuperados en la cobertura. Los estados no se actualizan en directo.</div>{results.length ? <div className="cards">{results.slice((page-1)*pageSize,page*pageSize).map(row => <article key={row.id} className="auction"><div className="card-tags"><Tag type={tagType(row.status)} size="sm">{row.status}</Tag><span>{row.categories.join(' · ')}</span></div><p className="reference">{row.id}</p><h3><button onClick={() => setSelected(row)}>{row.description || 'Consultar descripción en el BOE'}</button></h3><p className="location">{[row.towns.join(', '),row.provinces.join(', ')].filter(Boolean).join(' · ') || 'Ubicación pendiente de recuperar'}</p><dl className="card-facts"><div><dt>Valor de subasta</dt><dd>{currency(row.value)}</dd></div>{row.facts?.surfaceM2 && <div><dt>Superficie publicada</dt><dd>{row.facts.surfaceM2.toLocaleString('es-ES')} m²{row.facts.surfaceKind === 'construida' ? ' construidos' : ''}</dd></div>}<div><dt>Cierre</dt><dd>{date(row.end)}</dd></div></dl><Outcome row={row} compact/><div className="card-footer"><span>Consultada {date(row.checkedAt)}</span><Button kind="ghost" size="sm" renderIcon={ArrowRight} onClick={() => setSelected(row)} aria-label={`Ver ficha ${row.id}`}>Ver ficha</Button></div></article>)}</div> : <div className="empty"><SearchIcon size={32}/><h3>No hay coincidencias en el catálogo</h3><p>Prueba con otros filtros o consulta el portal oficial para ampliar la búsqueda.</p><Button kind="tertiary" onClick={() => {setFilters(defaults);setPage(1);}}>Restablecer filtros</Button></div>}{results.length > 0 && <Pagination page={page} pageSize={pageSize} pageSizes={[12,24,48]} totalItems={results.length} backwardText="Página anterior" forwardText="Página siguiente" itemsPerPageText="Por página:" pageRangeText={(_,total) => `de ${total} páginas`} itemRangeText={(min,max,total) => `${min}–${max} de ${total}`} onChange={({page,pageSize}) => {setPage(page);setPageSize(pageSize);}}/>}</>}
      </section></div>
      {catalog && results.length > 0 && <ResultsMap rows={results} onSelect={setSelected}/>}
      <section id="cobertura" className="coverage"><p className="eyebrow">SOBRE LOS DATOS</p><h2>Qué incluye este catálogo</h2><p>Selección del BOE por tipo de bien «Inmuebles» y provincia «Valencia/València», según la ubicación del bien. Incluye las subastas recuperadas mediante las consultas por estado y por fecha de inicio indicadas abajo. El histórico desde 2016 está incompleto. Las subastas con varios lotes pueden contener otros bienes: consulta cada lote en el BOE. «No consta» indica que no se ha recuperado ese dato. Las fichas sin fecha de inicio quedan fuera del filtro por año.</p>{catalog && <details><summary>Ver las {catalog.scans.length} consultas realizadas</summary><div className="coverage-table"><table><thead><tr><th>Consulta</th><th>Bienes</th><th>Recuperadas</th><th>Resultados BOE</th></tr></thead><tbody>{catalog.scans.map((scan,index) => <tr key={index}><td>{scan.from ? `${scan.from} → ${scan.to}` : scan.state === 'EJ' ? 'Activas' : 'Próximas'}</td><td>{scan.category}</td><td>{scan.imported}</td><td>{scan.total ?? 'No confirmado'}</td></tr>)}</tbody></table></div></details>}<p>Antes de tomar una decisión, comprueba siempre el estado, los lotes y la documentación en el <a href="https://subastas.boe.es/">portal oficial</a>.</p></section>
      <footer>Subastas BOE · Proyecto independiente, sin afiliación con el BOE.<a href="https://github.com/jorpago2/subastas-boe">Código del proyecto <ArrowUpRight size={16}/></a></footer>
    </main>
    <Modal open={!!selected} passiveModal onRequestClose={() => setSelected(null)} modalLabel={selected?.id || ''} modalHeading="Ficha de la subasta" closeButtonLabel="Cerrar ficha" size="lg">{selected && <div className="detail"><Tag type={tagType(selected.status)}>{selected.status}</Tag><h3>{selected.description}</h3><p>{selected.statusText}</p><DocumentSummary row={selected}/><Outcome row={selected}/><dl>{[['Tipo',selected.auctionType],['Inicio',date(selected.start)],['Cierre',date(selected.end)],['Valor de subasta',currency(selected.value)],['Precio tasado',currency(selected.facts?.appraisalValue)],['Precio tasado por m²',selected.facts?.appraisalPricePerM2 != null ? `${selected.facts.appraisalPricePerM2.toLocaleString('es-ES',{maximumFractionDigits:0})} €/m²` : 'No consta'],['Superficie publicada',selected.facts?.surfaceM2 ? `${selected.facts.surfaceM2.toLocaleString('es-ES')} m² (${selected.facts.surfaceKind})` : 'No consta'],['Vivienda habitual',factValue(selected.facts,'habitual')],['Ocupación documentada',factValue(selected.facts,'occupancy')],['Cargas documentales',factValue(selected.facts,'charges')],['Depósito',currency(selected.deposit)],['Puja mínima',selected.minimumBidText],['Lotes',selected.lots],['Localidad',selected.towns.join(', ')],['Provincia',selected.provinces.join(', ')],['Autoridad gestora',selected.authority],['Última comprobación',date(selected.checkedAt)]].map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value || 'No consta'}</dd></div>)}</dl>{mapEmbedUrl(selected) && <section className="map" aria-label="Mapa de ubicación"><h4>Ubicación del inmueble</h4><iframe title={`Mapa de ${selected.description}`} src={mapEmbedUrl(selected)} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen></iframe><p>Google Maps calcula la posición a partir de la dirección publicada; comprueba la ficha oficial.</p></section>}<p className="detail-note">Los importes y estados documentales proceden de la ficha o sus anexos cuando se indican. «No consta» no equivale a ausencia; comprueba siempre el BOE. Para subastas con lotes, consulta sus condiciones individuales.</p><Documents row={selected}/><Button as="a" href={selected.url} target="_blank" rel="noreferrer" renderIcon={ArrowUpRight}>Abrir ficha oficial</Button>{selected.announcement && <a className="announcement" href={`https://www.boe.es/diario_boe/txt.php?id=${selected.announcement}`} target="_blank" rel="noreferrer">Anuncio {selected.announcement}</a>}</div>}</Modal>
  </Theme>;
}
createRoot(document.getElementById('root')).render(<App/>);
